version: '3.9'

volumes:
  postgres-data:
    driver: local

networks:
  appnet:
    driver: bridge

services:
  db:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: DockerfilePostgres
    ports:
      - 5438:5432
