version: '3.9'

volumes:
  postgres-data:
    driver: local
  jenkins-data :

networks:
  appnet:
    driver: bridge

services:
  db:
    build: .
    ports:
      - 5432:5432
  jenkins :
    image : jenkins/jenkins:lts
    restart : always
    ports :
      - "8080:8080"
    volumes :
      - jenkins-data:/var/jenkins_home
    environment :
      - JENKINS_USER=admin
      - JENKINS_PASS=password

