server:
  port:
    8228

spring:
  application.name: backend-service

  jpa:
    properties:
      hibernate:
        ddl-auto : none
        show_sql: true
        use_sql_comments: true
        format_sql: true
        hbm2ddl :
          auto : update
    generate-ddl : false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  liquibase :
    change-log: main-changelog.xml


databases:
  postgres:
    port: 5438
    name: task_titans
    username: postgres
    password: postgres