server:
  port:
    8228

spring:
  application.name: backend-service

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${databases.postgres.port}/${databases.postgres.name}
    username: ${databases.postgres.username}
    password: ${databases.postgres.password}






databases:
  postgres:
    port: 5438
    name: task_titans
    username: postgres
    password: postgres